version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: rzq-react-vite-db
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rzq-reactjs-vite
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: rzq-react-vite-redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rzq-react-vite-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password123@db:5432/rzq-reactjs-vite
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - rzq_node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    command: |
      sh -c "npx prisma generate && npm run migration:run && npm run seed ; npm run dev"

volumes:
  postgres_data:
  redis_data:
  rzq_node_modules: